name: 'Flakiness Summary'
description: 'Run test suite multiple times and process results to uncover flakiness'
inputs:
  test-suite:
    description: 'Test suite to run'
    required: true
  commit-sha: 
    description: 'Commit to checkout'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test-suite }}
    - ${{ inputs.commit-sha }}