apiVersion: batch/v1
kind: CronJob
metadata:
  name: flakiness-summary
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: flakiness-summary
            image: TODO
          restartPolicy: Never